// This is an autogenerated file from Firebase Studio.
import {initializeApp, getApp, FirebaseApp} from 'firebase/app';
import {getFirestore} from 'firebase/firestore';
import { getAuth } from 'firebase/auth';

export const firebaseConfig = {
  projectId: 'studio-3921090023-25f63',
  appId: '1:997115219513:web:fe7fc8030f71f8530247e8',
  storageBucket: 'studio-3921090023-25f63.appspot.com',
  apiKey: 'AIzaSyCQN0MO3IhodZaj6XMUFaCQdnS9G6nxwgY',
  authDomain: 'studio-3921090023-25f63.firebaseapp.com',
  messagingSenderId: '997115219513',
};

let app: FirebaseApp;
try {
  app = getApp();
} catch (e) {
  app = initializeApp(firebaseConfig);
}

export const db = getFirestore(app);
export const auth = getAuth(app);
